/* Please note that this file is generated by the VulkanSharp's generator. Do not edit directly.

   Licensed under the MIT license.

   Copyright 2016 Xamarin Inc

   This notice may not be removed from any source distribution.
   See LICENSE file for licensing details.
*/

using System;
using System.Runtime.InteropServices;

namespace Vulkan.Linux
{
	unsafe public partial class MirSurfaceCreateInfoKhr : MarshalledObject
	{
		public UInt32 Flags {
			get { return m->Flags; }
			set { m->Flags = value; }
		}

		public MirConnection Connection {
			get { return m->Connection; }
			set { m->Connection = value; }
		}

		public MirSurface MirSurface {
			get { return m->MirSurface; }
			set { m->MirSurface = value; }
		}
		internal Linux.Interop.MirSurfaceCreateInfoKhr* m {

			get {
				return (Linux.Interop.MirSurfaceCreateInfoKhr*)native.Handle;
			}
		}

		public MirSurfaceCreateInfoKhr ()
		{
			native = Vulkan.Interop.Structure.Allocate (typeof (Linux.Interop.MirSurfaceCreateInfoKhr));
			Initialize ();
		}

		internal MirSurfaceCreateInfoKhr (NativePointer pointer)
		{
			native = pointer;
			Initialize ();
		}


		internal void Initialize ()
		{
			m->SType = StructureType.MirSurfaceCreateInfoKhr;
		}

	}

	unsafe public partial class WaylandSurfaceCreateInfoKhr : MarshalledObject
	{
		public UInt32 Flags {
			get { return m->Flags; }
			set { m->Flags = value; }
		}

		public wl_display Display {
			get { return m->Display; }
			set { m->Display = value; }
		}

		public wl_surface Surface {
			get { return m->Surface; }
			set { m->Surface = value; }
		}
		internal Linux.Interop.WaylandSurfaceCreateInfoKhr* m {

			get {
				return (Linux.Interop.WaylandSurfaceCreateInfoKhr*)native.Handle;
			}
		}

		public WaylandSurfaceCreateInfoKhr ()
		{
			native = Vulkan.Interop.Structure.Allocate (typeof (Linux.Interop.WaylandSurfaceCreateInfoKhr));
			Initialize ();
		}

		internal WaylandSurfaceCreateInfoKhr (NativePointer pointer)
		{
			native = pointer;
			Initialize ();
		}


		internal void Initialize ()
		{
			m->SType = StructureType.WaylandSurfaceCreateInfoKhr;
		}

	}

	unsafe public partial class XlibSurfaceCreateInfoKhr : MarshalledObject
	{
		public UInt32 Flags {
			get { return m->Flags; }
			set { m->Flags = value; }
		}

		public IntPtr Dpy {
			get { return m->Dpy; }
			set { m->Dpy = value; }
		}

		public Window Window {
			get { return m->Window; }
			set { m->Window = value; }
		}
		internal Linux.Interop.XlibSurfaceCreateInfoKhr* m {

			get {
				return (Linux.Interop.XlibSurfaceCreateInfoKhr*)native.Handle;
			}
		}

		public XlibSurfaceCreateInfoKhr ()
		{
			native = Vulkan.Interop.Structure.Allocate (typeof (Linux.Interop.XlibSurfaceCreateInfoKhr));
			Initialize ();
		}

		internal XlibSurfaceCreateInfoKhr (NativePointer pointer)
		{
			native = pointer;
			Initialize ();
		}


		internal void Initialize ()
		{
			m->SType = StructureType.XlibSurfaceCreateInfoKhr;
		}

	}

	unsafe public partial class XcbSurfaceCreateInfoKhr : MarshalledObject
	{
		public UInt32 Flags {
			get { return m->Flags; }
			set { m->Flags = value; }
		}

		public IntPtr Connection {
			get { return m->Connection; }
			set { m->Connection = value; }
		}

		public IntPtr Window {
			get { return m->Window; }
			set { m->Window = value; }
		}
		internal Linux.Interop.XcbSurfaceCreateInfoKhr* m {

			get {
				return (Linux.Interop.XcbSurfaceCreateInfoKhr*)native.Handle;
			}
		}

		public XcbSurfaceCreateInfoKhr ()
		{
			native = Vulkan.Interop.Structure.Allocate (typeof (Linux.Interop.XcbSurfaceCreateInfoKhr));
			Initialize ();
		}

		internal XcbSurfaceCreateInfoKhr (NativePointer pointer)
		{
			native = pointer;
			Initialize ();
		}


		internal void Initialize ()
		{
			m->SType = StructureType.XcbSurfaceCreateInfoKhr;
		}

	}

}
